[CmdletBinding()]param([Parameter(Mandatory)][string]$RequestPath,[switch]$ValidateOnly)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Full([string]$p){[IO.Path]::GetFullPath($p)}
function Inside([string]$root,[string]$path){$r=(Full $root).TrimEnd('\');$p=Full $path;$p-eq$r-or$p.StartsWith($r+'\',[StringComparison]::OrdinalIgnoreCase)}
function InRoot([string]$root,[string]$path,[switch]$Exists){$p=if([IO.Path]::IsPathRooted($path)){Full $path}else{Full(Join-Path $root $path)};if(-not(Inside $root $p)){throw "Path escapes registered root: $path"};if($Exists-and-not(Test-Path $p -PathType Leaf)){throw "Missing file: $path"};$p}
$configPath=Join-Path $PSScriptRoot 'broker.config.json';if(-not(Test-Path $configPath)){throw 'Protected broker config missing'}
$config=Get-Content -Raw $configPath|ConvertFrom-Json;$requestFile=Full $RequestPath;if(-not(Test-Path $requestFile -PathType Leaf)){throw 'Request file missing'}
$project=$null;foreach($p in @($config.projects)){if(Inside $p.root $requestFile){$project=$p;break}};if($null-eq$project){throw 'Request is outside registered projects'}
$root=Full $project.root;$req=Get-Content -Raw $requestFile|ConvertFrom-Json;$allowed=@('project_id','task_id','operation','prompt','reference_images','output_directory','max_images')
foreach($n in $req.PSObject.Properties.Name){if($n-notin$allowed){throw "Unknown field: $n"}}
if($req.project_id-ne$project.id){throw 'project_id mismatch'};if($req.task_id-notmatch'^[a-z0-9][a-z0-9._-]{0,79}$'){throw 'Invalid task_id'};if($req.operation-notin@('generate','edit')){throw 'Invalid operation'};if([string]::IsNullOrWhiteSpace($req.prompt)-or$req.prompt.Length-lt10-or$req.prompt.Length-gt12000){throw 'Invalid prompt'}
$max=if($null-ne$req.max_images){[int]$req.max_images}else{1};if($max-lt1-or$max-gt4){throw 'Invalid max_images'}
$refs=@();if($null-ne$req.reference_images){foreach($r in @($req.reference_images)){$refs+=InRoot $root ([string]$r)-Exists}};if($refs.Count-gt5){throw 'Too many references'};if($req.operation-eq'edit'-and$refs.Count-eq0){throw 'Edit requires a reference'}
if($project.delivery_policy-eq'staging'){$stage=InRoot $root 'Saved/AI_Temp/DelegatedImages';$rel=if([string]::IsNullOrWhiteSpace($req.output_directory)){"Saved/AI_Temp/DelegatedImages/$($req.task_id)"}else{[string]$req.output_directory};$out=InRoot $root $rel;if(-not(Inside $stage $out)){throw 'Output must remain in delegated staging'}}elseif($project.delivery_policy-eq'approval-before-copy'){if(-not[string]::IsNullOrWhiteSpace($req.output_directory)){throw 'output_directory forbidden by policy'};$out=Join-Path $PSScriptRoot "outputs\$($project.id)\$($req.task_id)"}else{throw 'Unknown delivery policy'}
if($ValidateOnly){[ordered]@{status='validated';project_id=$project.id;delivery_policy=$project.delivery_policy;output_directory=$out}|ConvertTo-Json;exit 0}
$gpt=Full $config.gpt_codex_home;$generated=Join-Path $gpt 'generated_images';$lock=$null
try{$lock=[IO.File]::Open((Join-Path $PSScriptRoot 'image.lock'),'OpenOrCreate','ReadWrite','None')}catch{throw 'Another image task is running'}
try{New-Item -ItemType Directory -Path $out -Force|Out-Null;$before=@{};Get-ChildItem $generated -Filter *.png -File -Recurse|ForEach-Object{$before[$_.FullName]=$true};$logs=Join-Path $out '.bridge';New-Item -ItemType Directory $logs -Force|Out-Null
$prompt="Use built-in image generation to $($req.operation) no more than $max image(s). Never use OPENAI_API_KEY. Do not modify project files or reproduce third-party branding. Request: $($req.prompt)"
$args=@('exec','--sandbox','workspace-write','--cd',$root,'--skip-git-repo-check','--ephemeral','--json','--output-last-message',(Join-Path $logs 'last-message.txt'));foreach($r in $refs){$args+=@('--image',$r)};$args+=$prompt;$old=$env:CODEX_HOME;try{$env:CODEX_HOME=$gpt;&codex @args 1>(Join-Path $logs 'events.jsonl') 2>(Join-Path $logs 'progress.log');$ec=$LASTEXITCODE}finally{$env:CODEX_HOME=$old};if($ec-ne0){throw "GPT Codex failed: $ec"}
$new=@(Get-ChildItem $generated -Filter *.png -File -Recurse|Where-Object{-not$before.ContainsKey($_.FullName)}|Sort-Object LastWriteTime);if($new.Count-eq0-or$new.Count-gt$max){throw "Unexpected image count: $($new.Count)"};Add-Type -AssemblyName System.Drawing;$arts=@();$i=0;foreach($f in $new){$i++;$d=Join-Path $out('image-{0:D2}.png'-f$i);Copy-Item $f.FullName $d -Force;$im=[Drawing.Image]::FromFile($d);try{$w=$im.Width;$h=$im.Height}finally{$im.Dispose()};$stream=[IO.File]::OpenRead($d);try{$sha=[Security.Cryptography.SHA256]::Create();try{$hash=([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-','').ToLower()}finally{$sha.Dispose()}}finally{$stream.Dispose()};$arts+=[ordered]@{path=$d;sha256=$hash;width=$w;height=$h}}
$manifest=[ordered]@{schema_version=1;status='completed';project_id=$project.id;task_id=$req.task_id;delivery_policy=$project.delivery_policy;production_approved=$false;provider='Codex built-in image generation via ChatGPT login';artifacts=$arts};$json=$manifest|ConvertTo-Json -Depth 6;[IO.File]::WriteAllText((Join-Path $out 'result.json'),$json,(New-Object Text.UTF8Encoding($false)));$json}finally{if($null-ne$lock){$lock.Dispose()}}
